/*
 * Sematext Cloud API
 *
 * API Explorer provides access and documentation for Sematext REST API. The REST API requires the API Key to be sent as part of `Authorization` header. E.g.: `Authorization : apiKey e5f18450-205a-48eb-8589-7d49edaea813`.
 *
 * API version: v3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package stcloud

import (
	"encoding/json"
	"time"
)

type TokenDto struct {
	CreatedAt time.Time `json:"createdAt,omitempty"`
	Enabled bool `json:"enabled,omitempty"`
	Id int64 `json:"id,omitempty"`
	Name string `json:"name,omitempty"`
	Readable bool `json:"readable,omitempty"`
	Token string `json:"token,omitempty"`
	Writeable bool `json:"writeable,omitempty"`
}

// UnmarshalJSON accepts both epoch-millis numbers (what the Sematext API
// currently sends) and RFC3339 strings (what the OpenAPI spec declares).
func (t *TokenDto) UnmarshalJSON(data []byte) error {
	type Alias TokenDto
	aux := struct {
		CreatedAt json.RawMessage `json:"createdAt,omitempty"`
		*Alias
	}{Alias: (*Alias)(t)}
	if err := json.Unmarshal(data, &aux); err != nil {
		return err
	}
	if len(aux.CreatedAt) == 0 || string(aux.CreatedAt) == "null" {
		return nil
	}
	var ms int64
	if err := json.Unmarshal(aux.CreatedAt, &ms); err == nil {
		t.CreatedAt = time.UnixMilli(ms)
		return nil
	}
	return json.Unmarshal(aux.CreatedAt, &t.CreatedAt)
}
